### ISSUE TITLE
Feature request: be able to edit a tag's color

### ISSUE THREAD

**Issue by Shanghi** [brisqapp/issue-tracker#11]
I ended up not liking the first color on the list so had to destroy all those tags and add them back using a much more suitable color.

**Comment by ashgrover** [comment]
Yes, I understand, it would be good to not only change color but also edit the text. I do plan to improve Label creation/modification so this feature will eventually get there.

Currently, I'm working hard on mobile apps so I'll come back to supporting desktop app as soon as I've rolled out stable mobile apps.

Thanks for the feature request.

**Comment by ashgrover** [comment]
v0.5.0 now supports editing labels.
