### ISSUE TITLE
Excel, CSV export

### ISSUE THREAD

**Issue by DebDak** [brisqapp/issue-tracker#17]
Ash,
Congrats again on creating a great application.  Simple, fast, powerful.

So far the only feature request I have is to provide a CSV or Excel export of the board data.  Perhaps I am old school but I would sleep better at night knowing that I can access my data in the event of a disaster with your code/operations.  May we never experience a disaster with Brisqi (!) but the safety net would be much appreciated.

Keep up the great coding and listening to your early customers and you will ROCK it!
Deb

**Comment by ashgrover** [comment]
Hi Deb,

Thank you for your kind words I appreciate it. I'm glad you're finding the app useful.

If your concern is backup of data, then Brisqi creates backup of your data at two places:

1) ~/Library/Application Support/Brisqi/backup.brisqi
2) ~/Library/Application Support/Brisqi/Backup directory

In your case, you can just copy the backup.brisqi file and store it somewhere safe. This file is automatically created when you close Brisqi. You can also manually create backups by going to Settings->Backup Data within Brisqi app.

To restore your data, just place the same backup.brisqi file back into the location mentioned in 1) and then you can go to Settings->Restore Data within Brisqi app.

The Backup directory mentioned in 2) stores database files and backup.brisqi file of last 5 days Brisqi app was used. This is a precautionary measure put in place to ensure user data is not lost.

Also, in case you lose your password and can't access cloud data, you can always sync your data back using the backup file after your password has been reset.

Please let me know if that clarifies some of the concerns.

Thank you,
Ash

**Comment by ashgrover** [comment]
This feature is available in v0.6.2 with Basic and Standard plan. Closing this issue.

**Comment by el3um4s** [comment]
I just bought the Brisqi Basic plan because I am interested in the function to export boards as CSV. But I can't figure out how to do it.
