### ISSUE TITLE
move list from one board to another?

### ISSUE THREAD

**Issue by ckhalleran** [brisqapp/issue-tracker#19]
Are there plans to allow moving a list from one board to another (drop it on another board, in the navigation pane)? I'm using the free Windows version... hoping to update to Standard version.

**Comment by ashgrover** [comment]
Hi,

Yes it has been already implemented and will be released in the next version(v0.6.0) soon.

Thanks

**Comment by ashgrover** [comment]
This feature has been implemented. Closing this issue.
