### ISSUE TITLE
Zoom in shortcut doesn't work

### ISSUE THREAD

**Issue by Herbherth** [brisqapp/issue-tracker#20]
Just a small bug report:
I'm using windows 10
"Ctrl -" works fine to zoom out
"Ctrl 0" no problem
"Ctrl +" nothing happens

I don't think it is an important bug because I don't even use it. I just found the software and was testing the options when I noticed it. Manually clicking in the settings options and zoom in works fine though.

If I find anything else I will let you know ;D #

**Comment by ashgrover** [comment]
Try Ctrl Shift +. Since + is typed using Shift + '=' so I specified '+' instead. I'll probably clarify it a bit more in the View menu.

**Comment by ckhalleran** [comment]
Hi Ash, on Chrome, IE11 and Edge, the shortcut for zoom in is "Ctrl =" that way you can just leave the Ctrl key pressed, along with either 0, - or = (on top row of keyboard) to switch between zoom levels.

**Comment by yujia21** [comment]
I'm on Ubuntu 20.04 and I seem to have the opposite problem:
"Ctrl -" doesn't work
"Ctrl 0" works
"Ctrl +" works **without** shift (Ctrl =), doesn't work with shift (Ctrl +)

**Comment by ashgrover** [comment]
@yujia21 I was about to comment and close this issue.

In v0.7.2, Zoom-in happens with "Ctrl Shift =".

Now in v0.7.3(released on Feb 12), Zoom-in happens with "Ctrl =". This change was made to be consistent with other key shortcuts.

Closing this issue.
