### ISSUE TITLE
Label selector doesn't scroll on desktop

### ISSUE THREAD

**Issue by dormerod** [brisqapp/issue-tracker#21]
**Brisqi version:** 0.7.3

**Brisqi plan:** standard

**Device:** desktop (only)

**Environment:** Fedora 34 (AppImage)

## What happened?

I was creating lots of labels and using them on my cards.

When I went to `Select Labels` on the card modal, I wasn't able to scroll down and select my newly created labels, as you can see in the screenshot:

![label-scrolling](https://user-images.githubusercontent.com/7741478/160084753-4b1fddc4-f78b-4ef0-ad73-bb98c0cfe14f.png)

## What I expected to happen

I thought there would be a scrollbar that would let me scroll down using the mouse or the scroll wheel.

## Steps to reproduce

Use the desktop app (this bug doesn't affect mobile) and:

1. create tens of labels (this needed more than 30 on my screen)
2. create a card
3. click on the card to open its modal view
4. click on `Select Labels`
5. try to select one of the newer labels at the bottom of the list.

**Comment by ashgrover** [comment]
Thanks for reporting this bug. It will be fixed in the next version(v0.8.0).

**Comment by ashgrover** [comment]
This issue is now fixed in v0.8.0. Closing this issue.
