### ISSUE TITLE
Desktop app slow to start when offline

### ISSUE THREAD

**Issue by dormerod** [brisqapp/issue-tracker#22]
**Brisqi version:** 0.7.3

**Brisqi plan:** standard

**Device:** desktop

**Environment:** Fedora 34 (AppImage)

## What happened?

I was trying to use Brisqi while completely offline. The app opened, but spent a long time loading (presumably looking for a server) before eventually displaying my boards.

## What I expected to happen

I expected the app to load as quickly as it normally does and work in an offline environment.

## Steps to reproduce

To reproduce:

1. use a non-mobile device
2. disconnect from wifi, ethernet etc
3. start Brisqi
4. observe how long it takes to start.

**Comment by ashgrover** [comment]
@dormerod Thanks for reporting this issue. 
I'm aware of this issue as I also experienced it. I've been working on the next version of Brisqi (v0.8.0) since last week and it specifically fixes this issue.

**Comment by ashgrover** [comment]
Brisqi v0.8.0 now includes startup performance improvements and also resolves this issue. Closing this issue.
