### ISSUE TITLE
Long subtask text gets clipped in desktop app

### ISSUE THREAD

**Issue by dormerod** [brisqapp/issue-tracker#24]
**Brisqi version:** 0.7.3

**Brisqi plan:** standard

**Device:** desktop

**Environment:** Fedora 34 (AppImage)

## What happened?

While struggling to describe tasks concisely, I entered a long piece of text while creating a subtask.

The text (as displayed) was clipped to a single line, though Brisqi did save the full text (which is visible on mobile).

Here's a screenshot of the problem:

![subtask-text](https://user-images.githubusercontent.com/7741478/160091655-a83e518c-fb2f-4368-9ead-c19008c8c113.png)

## What I expected to happen

I thought that I would be able to read the full description of subtasks while working in the desktop app.

## Steps to reproduce

1. create a card and open the card modal
2. create a subtask with a ridiculously verbose description
3. see how only the first line of wrapped text is visible.

**Comment by ashgrover** [comment]
Thanks for reporting. This will be fixed in v0.8.0 as well.

It was strange that long text doesn't show up because it should have, if the subtask with long text is edited again and if a space is added, then it shows up. It is indeed a bug which didn't occur in previous version of Brisqi.

**Comment by ashgrover** [comment]
This issue is now fixed in v0.8.0. Closing this issue.
