### ISSUE TITLE
Text search becomes clogged with completed cards

### ISSUE THREAD

**Issue by dormerod** [brisqapp/issue-tracker#26]
This is not so much a bug as a UX suggestion.

After working on a board for some time (one that's not for a short-lived project) and accumulating a lot of "done" cards, the free text `Search board...` function begins to decline in usefulness. It becomes clogged with many completed tasks which are no longer relevant.

## Some ideas for how to improve this

1. **(not too magic)** When using the `Search board...` function, allow the user to click or hit `Enter` to filter the cards on the board by those containing the typed text. This would also probably require a "clear filters" feature, which would also be an improvement for label filtering, but obviously makes the implementation more complex. This could either replace the current search behaviour, or complement it.
2.  **(a little magic)** Add a feature which allows users to mark a card as "Done" and exclude those cards from search results. A nice-to-have addition could include some magic for moving the card to the (top of the) rightmost list when it's marked as done.
3.  **(very magic)** Allow lists to be configured as "Done" lists. So, you may have one or more user defined lists (probably) on the right side of the board which exclude their cards from search but still allow some sort of user post processing (e.g. maybe someone wants to do a retrospective on all their completed tasks periodically and use the board to track it).

From my perspective, 1 is the best long-term solution, but 2 could be a easier in the short term (depending on how you like to work). I added 3 for completeness, but honestly it feels so bad that I'm thinking about deleting it :sweat_smile:

Interested to here any thoughts.

**Comment by ashgrover** [comment]
@dormerod Thanks for the suggestion. When I search for cards, sometimes I want to search them in Done lists too to check how I resolved that card or if there are notes/comments in that card. What I can do is add an option in search view to let users exclude lists from the search. This is similar to your 3rd option but instead of marking lists as "Done" and then excluding it in search results, the user decides which lists to exclude. I do need to revamp search feature a bit so I'll include an option to exclude lists as well. 

Good suggestion. Thanks again.

**Comment by dormerod** [comment]
> What I can do is add an option in search view to let users exclude lists from the search.

That's a good idea. In that case, the user experience is likely to depend on how easy it is to remove things you're not interested in (and as a possible future enhancement, Brisqi remembers which lists are selected (as an alternative to setting defaults)).

I meant to come back to this and edit it because I realised my thinking around this was very desktop-centric when using the mobile app the next day. Given the mobile experience (which is quite good), I can see why you built it the way you did.

**Comment by ashgrover** [comment]
This is now resolved with list filters in search functionality.
