### ISSUE TITLE
Search the board for unlabelled cards

### ISSUE THREAD

**Issue by dormerod** [brisqapp/issue-tracker#29]
Currently, it's possible to filter the board to only display cards with a selected label (which is a fantastic feature!).

There's another story where you want to find cards that you haven't labelled (perhaps no labels means they need to be triaged?).

When selecting `Search board...` it would be _very_ nice to have a "magic" option called `Unlabelled` in some other colour like grey, at the start of the label list.

**Comment by ashgrover** [comment]
Thanks for suggesting this feature. I can see this feature being a useful and probably shouldn't take too much time to implement. I'll push this feature for v0.8.0.

**Comment by ashgrover** [comment]
This feature is now available in v0.8.0. The filter "No Label" is added to filter unlabeled cards. Closing this issue.
