### ISSUE TITLE
Ability to change backup location

### ISSUE THREAD

**Issue by Dricey** [brisqapp/issue-tracker#3]
I see it is possible to make a backup and restore a backup. However the backup location is mystified at the moment.
Changing the backup location makes it possible to move it to a new laptop installation.

p.s. yeah first ticket! Great work on the application so far. Currently ticks all the boxes for me in my way of working

**Comment by ashgrover** [comment]
Hi Dricey, 

Yes, first ticket. I've been waiting for someone to make that first ticket:smiley:. Thank you for your feedback and choosing Brisqi.

Backup and restore certainly happens behind the scenes, but I see your point. I had been thinking about giving the user ability to change the location as well. I've put it in my backlog, so I'll include this feature eventually.

In the meantime, you can copy the backup file from:

On Windows - %AppData%\Brisqi\backup.brisqi
On Linux(Ubuntu) - /home/user/.config/Brisqi/backup.brisqi

When you're on a new laptop, just copy the file back into the same location and from Brisqi app, restore the data.

Thanks,
Ash

**Comment by schuldoi** [comment]
Hi Ash,

great tool so far. I heavily use it. 

Is there also a possibility to create a backup on MacOS? I could not find backup.brisqi in the .config folders.

Regards and many thanks in advance
Dominik

**Comment by ashgrover** [comment]
Hi Dominik,

Thanks for the feedback. I'm glad you found the app useful :)

For macOS the backup file's location is: ~/Library/Application Support/Brisqi/backup.brisqi

Thanks,
Ash

**Comment by schuldoi** [comment]
Hi Ash,

thanks a lot. Works for me :-)

Regards
Dominik

**Comment by ashgrover** [comment]
This feature has been implemented and is available with Basic and Standard plan. Closing this issue.
