### ISSUE TITLE
Clear filters option

### ISSUE THREAD

**Issue by dormerod** [brisqapp/issue-tracker#30]
When filtering the board by label (with many cards) it's easy to forget that you've applied one or more filters. And, when you have a lot of labels, it's not so easy to find all the labels you selected and unselect them.

A nice pattern might be to display a `Clear filters` link and/or icon (like many apps, e.g. Github, do) to remind the user that filters have been applied _and_ make it easy to clear them.

This will become even more important if #26 (suggestion 1) or #29 are implemented.

**Comment by ashgrover** [comment]
Added in v0.8.0. The Clear Filters button now shows up when a filter is applied. Closing this issue.
