### ISSUE TITLE
Display an icon on cards when they have a description

### ISSUE THREAD

**Issue by dormerod** [brisqapp/issue-tracker#31]
The icons which display completed tasks and presence/number of comments without viewing the card details are super cool and useful :+1:

For me at least, it would also be useful to display an icon (maybe three horizontal lines to indicate text) on cards where the description isn't empty to indicate that more information is available.

### Why would this be useful?

I'm not sure if this usage is typical (feel free to let me know if it's not), but most of my cards are just a title describing a task (and often one or two labels). If there's no description, I don't need to waste time clicking on the card to view the details.

If I have important information that provides context for completing the task, I'd naturally put it in the description. However, more and more I've noticed myself putting this information in comments so that the comment icon will prompt me to open the card details.

Not sure about others, but sometimes I really need to be prompted to remind myself of key details so that I don't forget key information about a job and do something stupid.

**Comment by ashgrover** [comment]
Thanks for suggesting this feature. This will be there in v0.8.0.

**Comment by ashgrover** [comment]
Added in v0.8.0. The description icon now shows up if a card has a description. Closing this issue.
