### ISSUE TITLE
Filter by: has due date

### ISSUE THREAD

**Issue by dormerod** [brisqapp/issue-tracker#32]
This feature is probably only nice to have, but would still be useful if it's not to much work to implement.

This would be another "magic" filter option like #29. This one would only display cards which have a due date on the board.

### Why would this be useful?

In my workflow at least, I only put a due date on something if it's important that it happens by a given date. Periodically, it's useful to be able to review everything that has a date on it and see upcoming tasks a few weeks before they're due. I'm finding myself duplicating tasks with due dates into my calendar to be sure I can see them approaching.

Most tasks on a kanban are are _soft_ and just need to be done "when possible". Anything where a due date has been set has a _hard_ deadline. This is the minimal overhead way of working with dates.

**Comment by ashgrover** [comment]
@dormerod Thanks for the suggestion. I can see this feature coming in handy. I can add another filter "Has Due Date" to label filters. I've put it in my backlog and will get there eventually as this is a low priority at the moment.

**Comment by holzee** [comment]
Would be definitely useful 📆

**Comment by ashgrover** [comment]
This feature is now available in the latest version of the app. Closing the issue.
