### ISSUE TITLE
Suggestion to have quicker way to add tag (right click menu choice, for a few favorite tags?)

### ISSUE THREAD

**Issue by ckhalleran** [brisqapp/issue-tracker#36]
It would be nice if you could configure specific tags such that they'd show up in right click menu... so you could more quickly apply those tags to a card. Currently you have to click 4 times to apply a tag. You might have 10 different tags in use, but only 2 that you use more frequently. Maybe you could configure those two tags to appear in the right click menu (like "DONE" or "URGENT")... although the rest of your tags would not need to appear in that right click menu (you'd have to go to the back of the card to apply those). You could still add those favorite tags from the back of the card too.

**Comment by ckhalleran** [comment]
I used an Autohotkey script to click at specific mouse coordinates. So if I have Brisqi open, and my mouse positioned over a card, I hit the shortcut for my Autohotkey script... and it clicks the card, clicks the Select Labels button, clicks my "DONE" tag", then clicks the Close button. I could have a different shortcut for another tag (maybe one that says "Not Applicable")

**Comment by ashgrover** [comment]
@ckhalleran I had definitely thought of including a label selection menu in the right click menu of the cards where it would show all the labels. I feel that showing recently used labels and not other labels would break the flow for the users if they want to apply other labels from the right click menu as well. For ex. I can imagine right clicking a card and wanting to apply a particular label only to find out that it's not one of the recently used so now I have to go to card details and then apply from there - it's a bit cumbersome. 

I believe showing all the labels in the right click menu would be a better option for the users. I'm thinking of showing a label menu in a compact form similar to the one you see under search board menu when filtering with labels and also thinking of replacing the label menu in card details with the one in compact form. 

Thanks for the suggestion.
Ash

**Comment by dormerod** [comment]
There might be a compromise where the right-click menu could show the x most common labels used (5 or 10?) and the last menu item expands to show the full list. Of course, that's starting to sound like two different features which could be released at different times. Just my 2 cents...

**Comment by ashgrover** [comment]
This feature is now available with v0.9.0
