### ISSUE TITLE
I don't understand how to export a board to CSV

### ISSUE THREAD

**Issue by el3um4s** [brisqapp/issue-tracker#37]
I just bought the Brisqi Basic plan because I am interested in the function to export boards as CSV. But I can't figure out how to do it.

**Comment by ashgrover** [comment]
@el3um4s Sorry for the late response, somehow I missed the Github notification. You should be able to export the boards to CSV by going to Board settings(ellipsis icon next to board name) - Edit, and under 'Export Board to CSV file' you should see Export button.

**Comment by el3um4s** [comment]
Oh, thank you 👍
