### ISSUE TITLE
Feature request : flush a list

### ISSUE THREAD

**Issue by holzee** [brisqapp/issue-tracker#40]
Would it be possible to clear all the cards in a list, ie. my done list I would like to flush from time to time. No need to archive, just flush instead of deleting and creating a new "done" list. Does it make sense? Truly loving your app !!

**Comment by ashgrover** [comment]
Hi, could you please clarify a bit more? Flushing would basically be deleting all the cards in a list correct?

In the spirit of simplicity, I prefer having only one 'delete' option for a list and that would be 'deleting the list entirely'.

That said, archiving feature is currently in the pipeline and will be released eventually and that will archive all the cards from a list which might satisfy your use case.

**Comment by holzee** [comment]
Puuurfect. Archiving seems what is needed here. Thanks for developing such a great app ❤️
