### ISSUE TITLE
Can't use Esc when hovering over modal

### ISSUE THREAD

**Issue by MusicDev33** [brisqapp/issue-tracker#44]
When I hover over a modal after clicking on a card in a list and hit Esc, the modal doesn't close, but when I move the mouse off of the modal, hitting Esc closes the modal.

I'm not sure if this is deliberate or not, so I'm not really sure what label to stick on this.

**Comment by ashgrover** [comment]
Thanks for catching this issue. It was not intentional, but I'll see if I can make it consistent.

**Comment by ashgrover** [comment]
It should be now resolved in v0.11.2.

**Comment by MusicDev33** [comment]
You are amazing, thank you so much @ashgrover
