### ISSUE TITLE
Feature Request: Printing

### ISSUE THREAD

**Issue by tomtinker** [brisqapp/issue-tracker#47]
Maybe I'm missing something obvious, but I can't find any print button. If Brisqi really doesn't have a printing function, it really needs one - especially for outdoor tasks. Most of my tasks are outdoors, and I can't take Brisqi outside on a sunny day because, unlike a printed list, phone/tablet screens cannot be viewed in bright sunlight. The ability to print out my task lists would make life so much easier. How about adding a printing function?

**Comment by ashgrover** [comment]
Hi @tomtinker 

Thanks for the suggestion. I'll take it into consideration for the future.

If you're on Basic/Standard plan, you can also convert a board to a CSV file by following - [How to export board to a CSV file](https://blog.brisqi.com/posts/how-to-export-to-csv) and printing the csv file.

**Comment by ashgrover** [comment]
The print feature for cards and list items has been implemented in version 0.13.0! 
Closing this issue.
