### ISSUE TITLE
Feature Request: Ability to Hide Label Text

### ISSUE THREAD

**Issue by carbon853** [brisqapp/issue-tracker#49]
Hello!

I think it would be nice to be able to minimize labels to reduce visual strain.

I do this currently by using a whitespace unicode character:

![Idea](https://user-images.githubusercontent.com/89618355/216749943-c73c50ca-92a1-490b-8b36-d4433ed0c260.png)

**Comment by ashgrover** [comment]
This feature is now available in v0.14.0. Closing this issue.
