### ISSUE TITLE
Labels / MacOS

### ISSUE THREAD

**Issue by policyoftruth** [brisqapp/issue-tracker#5]
I am hesitant to leave this issue as I'm sure it's something obvious that I am overlooking but on MacOS but I can't add labels! The UI is very nice and minimal. I've checked the top bar and the gear on the bottom to no avail. On an actual unit-of-work card, there is an "Add Label" button that brings up a "No labels configured" message. I've tried an alt-click, click, typing straight away... /shrug! (macOS big sur, 11.2.1)

Regardless, great work! I'm loving the minimalist nature of your application.

**Comment by ashgrover** [comment]
Hi @policyoftruth ,

Thank you for the feedback.

You have to add labels in the board first by going to Board Settings (3 dots next to board name at the top). I've shown it in a demo video on the website, you can take a quick look there too.

Currently you can't add labels directly from the card details but I'll be adding a way to do just that in the future release.


Ash

**Comment by ashgrover** [comment]
Add labels directly from cards is now supported.
