### ISSUE TITLE
Brisqi Android breaks on Clear All

### ISSUE THREAD

**Issue by JNavig8tr** [brisqapp/issue-tracker#50]
When using "clear all" on Android to clear open apps. Brisqi must be uninstalled and re installed to function. Occurs even if signed out.
Running Android 13 on Samsung S21 FE 5g

**Comment by ashgrover** [comment]
Hey,

Thanks for reporting the bug. I just pushed out an update with a fix
yesterday. Can you please try reinstalling the app and then running the app
again?

Thanks,
Ash
