### ISSUE TITLE
Markdown Code Blocks Are Not Wrapped

### ISSUE THREAD

**Issue by carbon853** [brisqapp/issue-tracker#51]
When placing a markdown code block in a comment, it can exceed the width of the underlying card without wrapping or scrolling locally:

![image](https://user-images.githubusercontent.com/89618355/217291719-2d2cd911-4da4-427d-aba4-e235567ec273.png)

```
_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=
```

Platform: Arch Linux

**Comment by ashgrover** [comment]
Thanks for reporting the issue. It's now resolved v0.11.2.
