### ISSUE TITLE
"Get Started" Deduplication

### ISSUE THREAD

**Issue by carbon853** [brisqapp/issue-tracker#54]
After reinstalling and syncing a few times I have accumulated several `Get Started` boards:

![](https://user-images.githubusercontent.com/89618355/217483514-66f4fffb-f7c2-4e9d-b43d-ce1d8ce62d35.png)
Platform: Arch Linux x64

Perhaps these could be deduplicated automatically, or (ideally) not added / merged into non-empty sync profiles.

**Comment by angemala** [comment]
I'm using windows and this happens every time I launch the program.

**Comment by ashgrover** [comment]
Thanks for reporting the issue. It should be resolved in v0.11.2.
