### ISSUE TITLE
Feature request: Add other columns to the "Move To..." context menu

### ISSUE THREAD

**Issue by awmottaz** [brisqapp/issue-tracker#56]
In the right-click context menu for a card, I would like the "Move To..." sub-menu to include options for moving the card to another column on the board.

<img width="1266" alt="Screenshot 2023-06-28 at 08 20 23" src="https://github.com/Brisqi/issue-tracker/assets/17735385/0f351c0d-7948-43de-a159-d7a52e22474d">

For example, "Move To..." > "Done".

**Comment by ashgrover** [comment]
Thanks for the feedback.
This feature is now available in v0.12.2.
