### ISSUE TITLE
New "Getting Started" board appears every time Brisqi is launched

### ISSUE THREAD

**Issue by angemala** [brisqapp/issue-tracker#57]
Using windows it seems that every time I launch the software, a new getting started board is added. I've tried multiple users, multiple computers, multiple windows OS. It seems that every time I launch a new board appears. It would be nice for this to not happen, or to be able to turn it off.
Note: It doesn't matter if there is a getting started board or not. It just creates a new one. A linux users was having a similar issue in another bug report.

**Comment by ashgrover** [comment]
Thanks for reporting the issue. It should be now resolved in v0.11.2.
