### ISSUE TITLE
option on list to have new cards added to bottom instead of top

### ISSUE THREAD

**Issue by ckhalleran** [brisqapp/issue-tracker#60]
New cards automatically appear at the top of a list. I've used Brisqi for thinking out rough draft of process flows, and in that case I typically would rather go from top to bottom. So if there was a setting that could be applied to a list, that might be helpful?

Regards,
Chris Halleran

**Comment by ashgrover** [comment]
Hi, you can do this by clicking on the + button at the bottom of the list:

![image](https://github.com/Brisqi/issue-tracker/assets/5951074/cf01da6d-0b09-4ee8-9c9a-01ad545465d3)
