### ISSUE TITLE
Clicking on links in descriptions will open the link but also start editing that description (Windows version)

### ISSUE THREAD

**Issue by Shanghi** [brisqapp/issue-tracker#8]
This is obviously very minor and it only takes a second to click "Done" to be able to use another link, but maybe in the future it could be investigated. Also, thank you very much for making this. I think it's already the nicest looking of its kind and feels good to use.

**Comment by ashgrover** [comment]
@Shanghi 

Thank you for the feedback. I'm glad you liked the app.

I noticed this issue as well, I've put it in my backlog and it will be fixed in the next version.

Regards,
Ash

**Comment by ghost** [comment]
In the Mac version, the link does not open at all.

**Comment by ashgrover** [comment]
This is fixed in v0.5.0 now.
